# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rPlaceApp', '0003_auto_20170628_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canplace',
            name='time_to_place',
        ),
    ]
