# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 01:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rPlaceApp', '0007_auto_20170629_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canplace',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canplace', to=settings.AUTH_USER_MODEL),
        ),
    ]
